channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - tabulate
  - pandoc >=2.7
  - pandoc-crossref
  - pytest
  - cookiecutter
  - watermark
  - pip
  - pip:
    - pandoc-include
    - pandoc-latex-admonition
