channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter                         # necessary to run notebooks
  - jupyterlab                      # necessary to run notebooks
  - tabulate                        # generate markdown tables 
  - pandoc >=2.7                     # necessary to compile the paper
  - pandoc-crossref                 # necessary to compile the paper
  - watermark                       # add metadata to notebooks
  - pip
  - pip:
    - pandoc-include                 # necessary to compile the paper
    - pandoc-latex-admonition        # necessary to compile the paper
